server:
  port: 8989

spring:
  datasource:
    url: jdbc:mysql://47.103.14.241:3306/HaoFangWang?characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池配置
    druid:
      # 最大连接数
      max-active: 30
      # 最小连接数
      min-idle: 5
      # 获取连接最大等待时间
      max-wait: 10000
      # 解决mysql自动断开8小时空闲连接
      validation-query: SELECT 'x'
      # 空闲连接检查时间间隔
      time-between-eviction-runs-millis: 60000
      # 空闲连接最小空闲时间
      min-evictable-idle-time-millis: 300000

  freemarker:
    charset: utf-8
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    suffix: .ftl
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      default_encoding: UTF-8
      auto_import: common/common.ftl as common
      classic_compatible: true

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml


